<a href="https://colab.research.google.com/github/allhoesnobros/Experiment-10/blob/main/experiment10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Experiment 10
Aayush Vishwakarma
25070123125

In [1]:
import pandas as pd
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
data={
    "Name":["A","B","C"],
    "Marks":[10,20,30]
}
df=pd.DataFrame(data)
print(df)

  Name  Marks
0    A     10
1    B     20
2    C     30

In [10]:
df.shape

(3, 2)

In [11]:
df.ndim

2

In [13]:
df.size

6

In [12]:
df.columns

Index(['Name', 'Marks'], dtype='object')

In [7]:
#Check datatype of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [8]:
#Access individual column
df["Name"]

0    A
1    B
2    C
Name: Name, dtype: object

In [9]:
df["Marks"]

0    10
1    20
2    30
Name: Marks, dtype: int64

In [14]:
#Access to the first row
df.loc[0,"Name"]

'A'

In [16]:
df.iloc[1]

Name      B
Marks    20
Name: 1, dtype: object

In [46]:
#Add a new column
df["Grade"]=["First class", "Distinction", "Second Class"]

In [47]:
print(df)

  Name Marks         Grade
0    A    81   First class
1    B    91   Distinction
2    C    30  Second Class

In [33]:
df.loc[0, "Marks"]= 81

In [34]:
print(df)

  Name Marks         Grade
0    A    81   First class
1    B    91   Distinction
2    C    30  Second Class

In [48]:
df.iloc[1,1]= 91
print(df)

  Name Marks         Grade
0    A    81   First class
1    B    91   Distinction
2    C    30  Second Class

In [41]:
#inplace will overwrite a data

In [49]:
#df.drop("Grade",axis=1,inplace=True)
df1=df.drop("Grade", axis=1)
print(df1)
print(df)

  Name Marks
0    A    81
1    B    91
2    C    30
  Name Marks         Grade
0    A    81   First class
1    B    91   Distinction
2    C    30  Second Class

In [50]:
#Perform basic statistical analysis
mean1=df["Marks"].mean()
mean1

np.float64(67.33333333333333)

In [51]:
min1=df["Marks"].min()
min1

30

In [52]:
print(df[df["Marks"]>80])

  Name Marks        Grade
0    A    81  First class
1    B    91  Distinction

In [53]:
max1=df["Marks"].max()
print(max1)

91